project:
  type: website

website:
  title: "Sungwoo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: note.qmd
        text: Note
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true



